### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
Basic fastlane structures for F-Droid (can also be used for Play Store, but that might need the Fastlane binaries for deployment). You might wish to move your screenshots into this structure, so screenshots appear on F-Droid as well; I didn't do this as I don't know from where (apart from the ReadMe) you might link to their current location, so I leave this to you. Be welcome to use my [Fastlane Cheat-Sheet](https://gitlab.com/snippets/1895688) to enhance this structure by adding more elements, like per-release screenshots, featureGraphic and more.

### CODE REVIEW

**Comment by abhinandanarya06** [comment]
Very Thanks for providing me the guide.

**Comment by IzzySoft** [comment]
Gladly! Thanks for merging that fast :+1: Are you planning to move the screenshots soon as well, or do you want to leave that for "later"? Asking for processing the MR at F-Droid. If you're about moving the screenshots right away, I'd suggest we wait for that before the next step "over there".

**Comment by abhinandanarya06** [comment]
screenshot moved and gradle wrapper upgraded.

**Comment by IzzySoft** [comment]
Thanks, looks good! Now we'd need a tag covering that (F-Droid picks fastlane from the same tag it builds the app from), then we can continue on the RFP.

**Comment by abhinandanarya06** [comment]
done from my side. please verify if it is done or not

**Comment by IzzySoft** [comment]
Yes, looks good, thanks! I'll advance the RFP then.

**Comment by abhinandanarya06** [comment]
Thank you too for helping in that

**Pull request merged**
